---
title: CrossTalkeR - Installation and Basic Execution
author:
- name: James S. Nagai
  affiliation: Institute for Computational Genomics,
               Faculty of Medicine,
               RWTH Aachen University,
               Aachen, 52074 Germany
- name: Nils B. Leimkühler
  affiliation: Department of Hematology and Stem Cell Transplantation,
               University Hospital Essen,
               Germany
- name: Vanessa Klöker
  affiliation: Institute for Computational Genomics,
               Faculty of Medicine,
               RWTH Aachen University,
               Aachen, 52074 Germany
- name: Michael T. Schaub
  affiliation:
     - Department of Computer Science,
       RWTH Aachen University,
       Aachen, Germany
- name: Rebekka K. Schneider
  affiliation:
    - Department of Hematology,
      Erasmus Medical Center,
      Rotterdam, 3015GD,
      the Netherlands
    - Department of Cell Biology,
      Institute for Biomedical Engineering,
      Faculty of Medicine,
      RWTH Aachen University,
      Aachen, 52074 Germany
    - Oncode Institute,
      Erasmus Medical Center,
      Rotterdam, 3015GD,
      the Netherlands
- name: Ivan G. Costa
  affiliation:
     - Institute for Computational Genomics,
       Faculty of Medicine,
       RWTH Aachen University,
       Aachen, 52074 Germany
output:
     html_document
vignette: |
      %\VignetteIndexEntry{CrossTalkeR-HumanMyfib}
      %\VignetteEngine{knitr::rmarkdown}
      %\VignetteEncoding{UTF-8}
---
# CrossTalkeR - Installation and Basic Execution

Here we like to give a short introduction on the installation and the basic usage of CrossTalkeR.

## Install

You can install and load the CrossTalkeR package with the simple commands below:

```{r, eval = FALSE}
install.packages("devtools")
devtools::install_github("https://github.com/CostaLab/CrossTalkeR", build_vignettes = TRUE)
require(CrossTalkeR)
```

There are the following possible system dependencies:
```{r, eval = FALSE}
libudunits2-dev
libgdal-dev
gdal-bin
libproj-dev
proj-data
proj-bin
libgeos-dev
```


Type any R code in the chunk, for example:
```{r}
mycars <- within(mtcars, { cyl <- ordered(cyl) })
mycars
```

