---
title: CrossTalkeR cookbook
author:
- name: James S. Nagai
  affiliation: Institute for Computational Genomics,
               Faculty of Medicine,
               RWTH Aachen University,
               Aachen, 52074 Germany
- name: Nils B. Leimkühler
  affiliation: Department of Hematology and Stem Cell Transplantation,
               University Hospital Essen,
               Germany
- name: Michael T. Schaub
  affiliation:
     - Department of Computer Science,
       RWTH Aachen University,
       Aachen, Germany
- name: Rebekka K. Schneider
  affiliation:
    - Department of Hematology,
      Erasmus Medical Center,
      Rotterdam, 3015GD,
      the Netherlands
    - Department of Cell Biology,
      Institute for Biomedical Engineering,
      Faculty of Medicine,
      RWTH Aachen University,
      Aachen, 52074 Germany
    - Oncode Institute,
      Erasmus Medical Center,
      Rotterdam, 3015GD,
      the Netherlands
- name: Ivan G. Costa
  affiliation:
     - Institute for Computational Genomics,
       Faculty of Medicine,
       RWTH Aachen University,
       Aachen, 52074 Germany
output:
     html_document
vignette: |
      %\VignetteIndexEntry{CrossTalkeR-cookbook}
      %\VignetteEngine{knitr::rmarkdown}
      %\VignetteEncoding{UTF-8}

---


# Version Info
```{r vignete0}
suppressPackageStartupMessages({require(CrossTalkeR)})
suppressPackageStartupMessages({require(igraph)})
suppressPackageStartupMessages({require(ggraph)})
suppressPackageStartupMessages({require(ggplot2)})

```

**R version**: `r R.version.string`

**Package version**: `r packageVersion("CrossTalkeR")`


# Generate Report Example

```{r vignete1, results="hide", warning=FALSE,message=F, output=FALSE}
paths <- c('CTR' = system.file("extdata",
                               "ctr_nils_bm_human.csv",
                               package = "CrossTalkeR"),
           'EXP' = system.file("extdata",
                               "exp_nils_bm_human.csv",
                               package = "CrossTalkeR"))
genes <- c('TGFB1')
output =  system.file("extdata", package = "CrossTalkeR")
data <- generate_report(paths,
                        genes,
                        out_path=paste0(output,'/'),
                        threshold=0,
                        out_file = 'vignettes_example.html',
                        output_fmt = "html_document",
                        report = FALSE)
```

# Individual Visualization

## CCI
```{r vignete2, results="hide", warning=FALSE,message=F, output=FALSE,fig.width=8,fig.height=8}
plot_cci(graph = data@graphs$CTR,
        colors = data@colors,
        plt_name = 'Example 1',
        coords = data@coords[V(data@graphs$CTR)$name,],
        emax = NULL,
        leg = FALSE,
        low = 0,
        high = 0,
        ignore_alpha = FALSE,
        log = FALSE,
        efactor = 8,
        vfactor = 12)

```
## GCI
```{r vignete3, results="hide", warning=FALSE,message=F, output=FALSE,fig.width=15,fig.height=15}
plot_ggi(graph = data@graphs_ggi$EXP_x_CTR,
         color = data@colors,name="EXP_x_CTR")

```

## Sankey plot
```{r vignete4, results="hide", warning=FALSE,message=F, output=FALSE,fig.width=15,fig.height=10}
plot_sankey(lrobj_tbl = data@tables$EXP_x_CTR,
            target = c("TGFB1"),
            ligand_cluster = NULL,
            receptor_cluster = NULL,
            plt_name = "TGFB1")

```


# Session information {.unnumbered}

```{r sessionInfo, echo=FALSE}
sessionInfo()
```
