---
title: "Annotation"
date:  "`r format(Sys.time(), '%d %B, %Y')`"
output:
  html_document:
      toc: yes
      toc_depth: 3
      theme: simplex
      self_contained: true
params:
  obj1: "path to obj"

---

```{r message=FALSE, warning=FALSE, echo=F, include=F}
require(igraph)
require(dplyr)
require(tibble)
require(tidyr)
require(patchwork)
require(stringr)
require(CrossTalkeR)
require(ggraph)
require(graphlayouts)
require(pals)
require(htmltools)
require(DT)
require(knitr)
```



```{r fig.align='center', fig.height=8, fig.width=15,warning=FALSE,echo=F}
path <-params$obj1
out <- c()
out1 <- list()
all_data <- readRDS(path)
for(i in 1:length(names(all_data@annot))){
     curr <- names(all_data@annot)[i]
     if(str_detect(curr, '_x_', negate = FALSE)){

       all_data@annot[[curr]]$size = unlist(lapply(all_data@annot[[curr]]$GeneRatio,
                                   function(x) round(eval(parse(text=x))*100,1)))
       all_data@annot[[curr]]$signal = as.factor(ifelse(grepl('up',all_data@annot[[curr]]$type),'up','down'))
       sel <- all_data@annot[[curr]] %>%
              dplyr::group_by(type) %>%
              dplyr::slice_max(order_by = -log10(p.adjust), n = 10)
       print(ggplot(sel, aes(y=reorder(Description,-log10(p.adjust)),x=-log10(p.adjust)))+
             geom_point(aes(size=size,colour=signal))+
             scale_colour_manual(values=c('navy','red'))+
             facet_grid(.~type)+theme_minimal())
   }
}

```
