---
title: "Report diferential analysis"
date:  "`r format(Sys.time(), '%d %B, %Y')`"
output:
  html_document:
      toc: yes
      toc_depth: 3
      theme: simplex
params:
  obj1: "path to obj"
  thr: 'percentage edges to plot'

---

```{r message=FALSE, warning=FALSE, echo=FALSE, include=FALSE, echo=FALSE}
require(igraph)
require(dplyr)
require(tibble)
require(tidyr)
require(patchwork)
require(stringr)
require(CrossTalkeR)
require(ggraph)
require(graphlayouts)
require(pals)


```

## Cell Cell Interaction Plot (CCI)

```{r fig.align='center', fig.height=8, fig.width=8,message=FALSE, warning=FALSE, echo=FALSE}
path <-params$obj1
thresh <- params$thr
all_data <- readRDS(path)
tmp_max <- 0
for(i in 1:length(names(all_data@tables))){
  curr <- names(all_data@tables)[i]
  if(str_detect(curr, '_x_', negate = FALSE)){
      var <- abs(E(all_data@graphs[[curr]])$MeanLR)
      if(max(var) > tmp_max){
        tmp_max <- max(var)
      }
  }
}
for(i in 1:length(names(all_data@tables))){
  curr <- names(all_data@tables)[i]
  if(str_detect(curr, '_x_', negate = FALSE)){
    curr_net <- all_data@graphs[[curr]]
    if(thresh!=0){
        low = (thresh/2)/100
        high = 0.5 + low
    }
    else{
        low = 0
        high = 0

    }
    plot_cci(curr_net,
               all_data@colors[V(curr_net)$name],
               paste0(curr,' CCI'),all_data@coords[V(curr_net)$name,],leg=TRUE,low=low,high = high,emax = tmp_max,log = TRUE)
  }
}
```

##  Frequency of Ligands and Receptors on CCI

```{r fig.align='center', fig.height=7, fig.width=12,message=FALSE, warning=FALSE,echo=FALSE}

for(i in 1:length(names(all_data@tables))){
  curr <- names(all_data@tables)[i]
  if(str_detect(curr, '_x_', negate = FALSE)){
    curr_net <- all_data@graphs[[curr]]
    in_deg_up <- table(all_data@tables[[curr]]$Ligand.Cluster[all_data@tables[[curr]]$MeanLR > 0])
    in_up <- tibble::tibble(as.data.frame(in_deg_up))
    in_deg_down <- table(all_data@tables[[curr]]$Ligand.Cluster[all_data@tables[[curr]]$MeanLR < 0])
    in_down <- tibble::tibble(as.data.frame(in_deg_down))
    in_down$Freq <- 0-in_down$Freq
    in_all <- dplyr::bind_rows(in_up,in_down)
    in_all$Expression <- ifelse(in_all$Freq<0,'Downregulated','Upregulated')
    in_all$rank <- ifelse(in_all$Freq<0,0,1)
    out_deg_up <- table(all_data@tables[[curr]]$Receptor.Cluster[all_data@tables[[curr]]$MeanLR > 0])
    out_up <- tibble::tibble(as.data.frame(out_deg_up))
    out_deg_down <- table(all_data@tables[[curr]]$Receptor.Cluster[all_data@tables[[curr]]$MeanLR < 0])
    out_down <- tibble::tibble(as.data.frame(out_deg_down))
    out_down$Freq <- 0-out_down$Freq
    out_all <- dplyr::bind_rows(out_up,out_down)
    out_all$Expression <- ifelse(out_all$Freq<0,'Downregulated','Upregulated')
    out_all$rank <- ifelse(out_all$Freq<0,0,1)
    p1 <- ggplot2::ggplot(in_all,ggplot2::aes(x=Freq,y=reorder(Var1,Freq*rank),fill=Expression))+
      ggplot2::geom_bar(stat = 'identity',position = "identity")+
      ggplot2::geom_text(ggplot2::aes(label=Freq),size=3.5)+
      ggplot2::scale_fill_manual(values=pals::coolwarm(2))+
      ggplot2::ggtitle('Ligands')+
      ggplot2::ylab('Cell')+
      ggplot2::xlab('Number of interactions')+
      ggplot2::theme_minimal()
    p2 <- ggplot2::ggplot(out_all,ggplot2::aes(x=Freq,y=reorder(Var1,Freq*rank),fill=Expression))+
      ggplot2::geom_bar(stat = 'identity',position = "identity")+
      ggplot2::geom_text(ggplot2::aes(label=Freq),size=3.5)+
      ggplot2::scale_fill_manual(values=pals::coolwarm(2))+
      ggplot2::ggtitle('Receptors')+
      ggplot2::ylab('Cell')+
      ggplot2::xlab('Number of interactions')+
      ggplot2::theme_minimal()
    print((p1+p2)+plot_annotation(title = curr,tag_levels = 'A'))
  }
}
```


## Cell Gene Interaction Plot (CGI):

*Highest degree connector candidate from the Largest Component*

```{r fig.align='center', fig.height=10, fig.width=10,message=FALSE, warning=FALSE,echo=FALSE}
for(i in 1:length(names(all_data@tables))){
  curr <- names(all_data@tables)[i]
  if(str_detect(curr, '_x_', negate = FALSE)){
    curr_net <- all_data@graphs_ggi[[curr]]
    aux <- components(curr_net, mode='weak')
    comp <- components(curr_net)
    sel <- 1
    for( j in 2:length(comp$csize)){
      if(comp$csize[j] > comp$csize[sel]){
        sel <- j
      }
    }
    sel_graph <- induced.subgraph(curr_net, V(curr_net)[comp$membership==sel])
    plot_ggi(sel_graph,color = all_data@colors)
  }
}
```



## Frequency of Sending(out-degree) Receiving (in-degree) genes of GCI

```{r fig.align='center', fig.height=6, fig.width=10,message=FALSE, warning=FALSE,echo=FALSE}
for(i in 1:length(names(all_data@tables))){
  curr <- names(all_data@tables)[i]
  if(str_detect(curr, '_x_', negate = FALSE)){
    curr_net <- all_data@graphs_ggi[[curr]]
    up_graph <- igraph::subgraph.edges(curr_net, E(curr_net)[E(curr_net)$MeanLR > 0])
    down_graph <- igraph::subgraph.edges(curr_net, E(curr_net)[E(curr_net)$MeanLR < 0])
    in_deg_up <- igraph::degree(up_graph, mode = 'in')
    in_deg_down <- igraph::degree(down_graph, mode = 'in')
    in_up <- tibble::tibble(genes = paste0(names(in_deg_up),'_up'), values=as.array(in_deg_up))
    in_down <- tibble::tibble(genes = paste0(names(in_deg_down),'_down'), values=as.array(in_deg_down))
    in_deg_data_up <-dplyr::top_n(in_up, 10, values)
    in_deg_data_down <- dplyr::top_n(in_down, 10, values)
    in_deg_data_down$values <- 0 -in_deg_data_down$values
    in_deg_data <- dplyr::bind_rows(in_deg_data_up,in_deg_data_down )
    in_deg_data$Expression <- ifelse(in_deg_data$values <0,'Downregulated','Upregulated')
    p1 <- ggplot2::ggplot(in_deg_data,ggplot2::aes(x=values,y=reorder(genes,values),fill=Expression))+
      ggplot2::geom_bar(stat = 'identity',position = "identity")+
      ggplot2::scale_fill_manual(values=pals::coolwarm(2))+
      ggplot2::ggtitle('Receiving')+
      ggplot2::ylab('Cell')+
      ggplot2::xlab('Number of interactions')+
      ggplot2::theme_minimal()
    out_deg_up <- igraph::degree(up_graph, mode = 'out')
    out_deg_down <- igraph::degree(down_graph, mode = 'out')
    out_up <- tibble::tibble(genes = paste0(names(out_deg_up),'_up'), values=as.array(out_deg_up))
    out_down <- tibble::tibble(genes = paste0(names(out_deg_down),'_down'), values=as.array(out_deg_down))
    out_deg_data_up <-dplyr::top_n(out_up, 10, values)
    out_deg_data_down <- dplyr::top_n(out_down, 10, values)
    out_deg_data_down$values <- 0-out_deg_data_down$values
    out_deg_data <- dplyr::bind_rows(out_deg_data_up,out_deg_data_down )
    out_deg_data$Expression <- ifelse(out_deg_data$values <0,'Downregulated','Upregulated')
    p2 <- ggplot2::ggplot(out_deg_data,ggplot2::aes(x=values,y=reorder(genes,values),fill=Expression))+
      ggplot2::geom_bar(stat = 'identity',position = "identity")+
      ggplot2::scale_fill_manual(values=pals::coolwarm(2))+
      ggplot2::ggtitle('Sending')+
      ggplot2::ylab('Cell')+
      ggplot2::xlab('Number of interactions')+
      ggplot2::theme_minimal()
    print((p2+p1)+plot_annotation(title = curr,tag_levels = 'A'))
  }
}
```
