---
title: "LR_Report"
date:  "`r format(Sys.time(), '%d %B, %Y')`"
output:
  html_document:
      toc: true
      toc_float: true
      number_sections: true
      theme: simplex
  pdf_document:
    latex_engine: xelatex
    dev: cairo_pdf

params:
  single: "path to single report template"
  comp: "path to comparative report template"
  obj1: "LRobj"
  obj2: "sankey gene plot"
  obj3: "sankey tf plot"
  thr: 'percentage of disregarded edges'
  sel: 'selected columns'
always_allow_html: true


---
```{r, echo=FALSE}
imgpath <- system.file("figures","logo1_40.png",package = "CrossTalkeR")
htmltools::img(src = knitr::image_uri(imgpath),
               alt = 'logo',
               style = 'position:absolute; top:0; right:0; padding:10px;width:40;height:40')
```

<style>
      div.blue { background-color:#e6f0ff; border-radius: 0.2%; padding: 10%;}
</style>

# Differential Analysis

## CCI - Cell Cell Interaction

```{r ccr, child='Comparative_Condition_cci.Rmd',eval=TRUE}
```

## CGI - Gene Cell Interaction

```{r ccr, child='Comparative_Condition_cgi.Rmd',eval=TRUE}
```
