---
title: "Report per condition"
date:  "`r format(Sys.time(), '%d %B, %Y')`"
output:
  html_document:
      toc: yes
      toc_depth: 3
      theme: simplex
params:
  obj1: "path to obj"
  thr: 'cutoff'

---

```{r message=FALSE, warning=FALSE, echo=F, include=F}
require(igraph)
require(dplyr)
require(tibble)
require(tidyr)
require(stringr)
require(patchwork)
require(LRAnalytics)

```

## Single Condition Cell Cell Interaction Plot (CCI)

```{r fig.align='center', fig.height=8, fig.width=8,message=FALSE, warning=FALSE, echo=F,fig.keep = 'all'}
path <-params$obj1
thr <- params$thr
all_data <- readRDS(path)
for(i in 1:length(names(all_data@tables))){
  curr <- names(all_data@tables)[i]
  if(!str_detect(curr, '_x_', negate = FALSE)){
      message(paste0('Printing CCI ',curr))
      curr_net <- all_data@graphs[[curr]]
      low <- thr
      plotLR_cci(curr_net,
                 all_data@colors[V(curr_net)$name],
                 paste0(curr,' CCI'),all_data@coords[V(curr_net)$name,],leg=TRUE,low=0,high=low/100)
   }
}
```

## Single Condition Cell Cell Frequency of Ligands and Receptors

```{r fig.align='center', fig.height=5, fig.width=15,message=FALSE, warning=FALSE, echo=F}

for(i in 1:length(names(all_data@tables))){
  curr <- names(all_data@tables)[i]
  if(!str_detect(curr, '_x_', negate = FALSE)){
    curr_net <- all_data@graphs[[curr]]
    in_deg <- table(all_data@tables[[curr]]$Ligand.Cluster)
    in_deg <- tibble::tibble(cells=names(in_deg),inter=in_deg)
    out_deg <-table(all_data@tables[[curr]]$Receptor.Cluster)
    out_deg <- tibble::tibble(cells=names(out_deg),inter=out_deg)
    p1 <- ggplot2::ggplot(in_deg,ggplot2::aes(x=inter,y=reorder(cells,inter),fill=cells))+
      ggplot2::geom_bar(stat="identity")+
      ggplot2::ggtitle('Ligands')+
      ggplot2::scale_fill_manual(values = all_data@colors, breaks = names(all_data@coords))+
      ggplot2::ylab('Cell')+
      ggplot2::xlab('Number of interactions')
   p2 <- ggplot2::ggplot(out_deg,ggplot2::aes(x=inter,y=reorder(cells,inter),fill=cells))+
      ggplot2::geom_bar(stat="identity")+
      ggplot2::scale_fill_manual(values = all_data@colors, breaks = names(all_data@coords))+
      ggplot2::ggtitle('Receptors')+
      ggplot2::ylab('Cell')+
      ggplot2::xlab('Number of interactions')
      lig_order <- all_data@rankings[[curr]]$ligand_count[names(all_data@colors)]
      rec_order <- all_data@rankings[[curr]]$receptor_count[names(all_data@colors)]
      df <- tibble(nodes=names(all_data@colors),ligand_ranking=lig_order,receptor_ranking=rec_order)
      df <- reshape2::melt(df)
      df$variable <- as.factor(df$variable)
      levels(df$variable) <- c(1,2)
      df$variable <- as.numeric(df$variable)
      p3 <- ggplot2::ggplot(df, ggplot2::aes(x=variable, y=value, color = nodes)) +
            ggplot2::geom_line(ggplot2::aes(color = nodes), size = 2) +
            ggplot2::geom_point(ggplot2::aes(color = nodes), size = 4) +
            ggplot2::scale_x_discrete(name ="variable",limits=c('ligand_frequency','receptor_frequency'))+
            ggplot2::scale_y_continuous(name='value',trans = "reverse", breaks = unique(df$value))+
            ggplot2::scale_color_manual(values = data@colors, breaks = names(data@coords))+
            ggplot2::labs(title = "Cells LR Frequency")+
            ggplot2::theme(legend.position = "none")+
            ggplot2::theme_minimal()
      
    print((p1+p2+p3)+plot_annotation(title = curr,tag_levels = 'A'))
  }
}
```
