---
title: "Report per condition"
date:  "`r format(Sys.time(), '%d %B, %Y')`"
output:
  html_document:
      toc: yes
      toc_depth: 3
      theme: simplex
params:
  obj1: "path to obj"
  thr: 'cutoff'

---

```{r message=FALSE, warning=FALSE, echo=FALSE, include=FALSE}
require(igraph)
require(dplyr)
require(tibble)
require(tidyr)
require(stringr)
require(patchwork)
require(CrossTalkeR)
require(factoextra)
require(ComplexHeatmap)
require("DT")

```

### Single Condition Cell Cell Interaction Plot (CCI)

*Here, the cell-cell interaction is provided for each phenotype separately*

```{r fig.align='center', fig.height=6, fig.width=6,message=FALSE, warning=FALSE, echo=FALSE,fig.keep = 'all'}
path <-params$obj1
thr <- params$thr
all_data <- readRDS(path)
for(i in 1:length(names(all_data@tables))){
  curr <- names(all_data@tables)[i]
  if(!str_detect(curr, '_x_', negate = FALSE)){
      message(paste0('Printing CCI ',curr))
      curr_net <- all_data@graphs[[curr]]
      low <- thr
      par(cex.axis=4, cex.lab=4)
      plot_cci(graph = curr_net,
                 colors = all_data@colors[V(curr_net)$name],
                 plt_name = paste0(curr,' CCI'),
                 coords = all_data@coords[V(curr_net)$name,],
                 leg=TRUE,
                 low=0,
                 high=low/100,
                 log = TRUE)
   }
}
```


### Pagerank Log Ratio

```{r fig.align='center',warning=FALSE,echo=FALSE,results='asis'}
for (i in 1:length(names(all_data@rankings))) {
  curr <- names(all_data@rankings)[i]
  if (!str_detect(curr, '_x_', negate = FALSE) & !str_detect(curr, 'ggi', negate = FALSE)) {
    cat(paste0("#### ", curr, "\n\n"))
    print(plot_bar_rankings(all_data, curr, "Pagerank", mode = "cci", top_num = 10))
    cat("\n\n")
  }
}
```